# Generated by Django 2.0.5 on 2018-06-08 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_news'),
    ]

    operations = [
        migrations.CreateModel(
            name='Goods',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shangpinmingchen', models.CharField(max_length=50)),
                ('pub_date', models.DateTimeField(verbose_name='date published')),
                ('shangpinleixing', models.CharField(max_length=5000)),
                ('shangpinjiage', models.CharField(max_length=5000)),
                ('shangpinshuoming', models.CharField(max_length=5000)),
                ('lianxidianhua', models.CharField(max_length=5000)),
            ],
        ),
    ]
