# Generated by Django 2.0.2 on 2018-06-17 02:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20180615_2008'),
    ]

    operations = [
        migrations.CreateModel(
            name='Style',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
            ],
        ),
        migrations.AlterField(
            model_name='goods',
            name='shangpinleixing',
            field=models.ForeignKey(on_delete=True, to='app.Style'),
        ),
    ]
